apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: elastic-external-exporter-sm-01
  labels:
    app: elastic-external-exporter-01
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: elastic-external-exporter-01
  endpoints:
  - port: metrics
    interval: 10s
    honorLabels: true
---

apiVersion: v1
kind: Service
metadata:
  name: elastic-external-exporter-01
  labels:
    app: elastic-external-exporter-01
spec:
  type: ExternalName
  externalName: 192.168.1.53
  clusterIP: ""
  ports:
  - name: metrics
    port: 9114
    protocol: TCP
    targetPort: 9114
---

apiVersion: v1
kind: Endpoints
metadata:
  name: elastic-external-exporter-01
  labels:
    app: elastic-external-exporter-01
subsets:
  - addresses:
    - ip: 192.168.1.53
    ports:
      - name: metrics
        port: 9114
        protocol: TCP
