alertmanager:
  enabled: false

prometheusOperator:
  createCustomResource: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
  additionalServiceMonitors:
    - name: "elasticsearch-exporter"
      selector: 
        matchLabels:
          app: elasticsearch-exporter
      endpoints: 
        - port: "http"
  ingress: 
    enabled: true
    hosts: [prometheus.127.0.0.1.xip.io]
    paths: [/] 
grafana:
  ingress: 
    enabled: true
    hosts: [grafana.127.0.0.1.xip.io]
    paths: [/] 
  dashboards:
    default:
      prometheus-stats:
        # Ref: https://grafana.com/dashboards/2
        gnetId: 2
        revision: 2
        datasource: Prometheus
      elasticsearch-stats:
        # Ref: https://grafana.com/grafana/dashboards/6483
        gnetId: 6483
        revision: 2
        datasource: Prometheus
