apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "service-monitor-external.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.service.externalName }}
  clusterIP: ""
  ports:
  - name: {{ .Values.service.port.name }}
    port: {{ .Values.service.port.servicePort }}
    protocol: {{ .Values.service.port.protocol }}
    targetPort: {{ .Values.service.port.targetPort }}
